// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfS96pH6OosGokJ6ZsUFKOgP9fMVw6m1c',
    appId: '1:247962472519:web:ab0c809104493196946162',
    messagingSenderId: '247962472519',
    projectId: 'flutterfirebase-8bfab',
    authDomain: 'flutterfirebase-8bfab.firebaseapp.com',
    databaseURL: 'https://flutterfirebase-8bfab-default-rtdb.firebaseio.com',
    storageBucket: 'flutterfirebase-8bfab.appspot.com',
    measurementId: 'G-00NWM9TKPY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCATMcm5lwFqRaYfxtjLWFbMnH9P7uK1SI',
    appId: '1:247962472519:android:472e1d163f237e2d946162',
    messagingSenderId: '247962472519',
    projectId: 'flutterfirebase-8bfab',
    storageBucket: 'flutterfirebase-8bfab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUvKArJTHx8Nn-w8irylVklbDi-xqiJLw',
    appId: '1:247962472519:ios:f23b50fe7b7cbe16946162',
    messagingSenderId: '247962472519',
    projectId: 'flutterfirebase-8bfab',
    storageBucket: 'flutterfirebase-8bfab.appspot.com',
    iosClientId:
        '247962472519-liv8k4oq07qfd3jdv5chhg3j01s7360o.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUvKArJTHx8Nn-w8irylVklbDi-xqiJLw',
    appId: '1:247962472519:ios:f23b50fe7b7cbe16946162',
    messagingSenderId: '247962472519',
    projectId: 'flutterfirebase-8bfab',
    storageBucket: 'flutterfirebase-8bfab.appspot.com',
    iosClientId:
        '247962472519-liv8k4oq07qfd3jdv5chhg3j01s7360o.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );
}
